events { worker_connections 1024; }

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    location /api/teams {
      proxy_pass http://team-service:8083;
      proxy_set_header Host $host;
    }
    location /api/persons {
      proxy_pass http://team-service:8083;
      proxy_set_header Host $host;
    }
    location /api/initiatives {
      proxy_pass http://planning-service:8082;
      proxy_set_header Host $host;
    }
    location /api/epics {
      proxy_pass http://planning-service:8082;
      proxy_set_header Host $host;
    }
    location /api/capacity {
      proxy_pass http://planning-service:8082;
      proxy_set_header Host $host;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri $uri/ /index.html;
    }
  }
}
