server:
  port: 8082

spring:
  application:
    name: planning-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/planning_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

team-service:
  url: ${TEAM_SERVICE_URL:http://localhost:8083}

logging:
  level:
    com.capacityplanning: INFO
